@host=api.hypertheory.com
### Get Account Info

GET http://localhost:8090 HTTP/1.1
Accept: application/json


### Get Order History
GET http://{{host}}/my/order-history HTTP/1.1
Accept: application/json


### GET Topics
GET http://{{host}}/learning/topics HTTP/1.1
Accept: application/json


### Versioned API
GET http://{{host}}/v2/my/account HTTP/1.2