@host = "api.hypertheory.com"


### Get Account Info

GET http://{{host}}/my/account HTTP/1.1

Accept: application/json


### Get Order History
GET http://{{host}}/my/order-history HTTP/1.1
Accept: application/json


### GET Topics
GET http://{{host}}/learning/topics HTTP/1.1
Accept: application/json

### Add A Topic

POST http://api.hypertheory.com/learning/topics HTTP/1.1
Content-Type: application/json

{
    "description": "A Thing"
}